# Generated by Django 4.1.7 on 2023-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, max_length=10, verbose_name='Цена'),
        ),
    ]
